name       : gimp-help
version    : 2.10.0
release    : 1
source     :
    - https://download.gimp.org/pub/gimp/help/gimp-help-2.10.0.tar.bz2 : 03804fed071b49e5810edd8327868659dfd9932fbf34d34189d56bd0ad539118
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  :
    - multimedia.graphics
    - ca : multimedia.graphics
    - da : multimedia.graphics
    - de : multimedia.graphics
    - el : multimedia.graphics
    - es : multimedia.graphics
    - fi : multimedia.graphics
    - fr : multimedia.graphics
    - it : multimedia.graphics
    - ja : multimedia.graphics
    - ko : multimedia.graphics
    - nl : multimedia.graphics
    - nn : multimedia.graphics
    - pt_br : multimedia.graphics
    - ro : multimedia.graphics
    - ru : multimedia.graphics
    - zh_cn : multimedia.graphics
summary    :
    - English help files for GIMP
    - ca : Catalan help files for GIMP
    - da : Danish help files for GIMP
    - de : German help files for GIMP
    - el : Greek help files for GIMP
    - es : Spanish help files for GIMP
    - fi : Finnish help files for GIMP
    - fr : French help files for GIMP
    - it : Italian help files for GIMP
    - ja : Japanese help files for GIMP
    - ko : Korean help files for GIMP
    - nl : Dutch help files for GIMP
    - nn : Norwegian help files for GIMP
    - pt_br : Brazilian Portuguese help files for GIMP
    - ro : Romanian help files for GIMP
    - ru : Russian help files for GIMP
    - zn_cn : Simplified Chinese help files for GIMP
description: |
    Help files for GIMP
patterns   :
    - ca : /usr/share/gimp/*/help/ca
    - da : /usr/share/gimp/*/help/da
    - de : /usr/share/gimp/*/help/de
    - el : /usr/share/gimp/*/help/el
    - es : /usr/share/gimp/*/help/es
    - fi : /usr/share/gimp/*/help/fi
    - fr : /usr/share/gimp/*/help/fr
    - it : /usr/share/gimp/*/help/it
    - ja : /usr/share/gimp/*/help/ja
    - ko : /usr/share/gimp/*/help/ko
    - nl : /usr/share/gimp/*/help/nl
    - nn : /usr/share/gimp/*/help/nn
    - pt_br : /usr/share/gimp/*/help/pt_BR
    - ro : /usr/share/gimp/*/help/ro
    - ru : /usr/share/gimp/*/help/ru
    - zh_cn : /usr/share/gimp/*/help/zhC_N
builddeps  :
    - pkgconfig(gimp-2.0)
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
